version: '3'
services:
  backend:
    build:
      context: ./SimulatorAPI
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  frontend:
    build:
      context: ./SimulatorUI
      dockerfile: Dockerfile
    ports:
      - "8081:80"
